- name: Setup tunnel endpoints
  hosts: targets
  become: yes
  become_method: su
  roles:
    - tunnel

- name: Setup tunnel bounce servers
  hosts: peers
  become: yes
  gather_facts: no
  roles:
    - endpoint
