- name: Setup tunnel endpoints
  hosts: endpoints
  become: yes
  become_method: su
  roles:
    - endpoint

- name: Setup tunnel bounce servers
  hosts: bounces
  become: yes
  gather_facts: no
  roles:
    - bounce
