- name: Update the cache and all packages
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install wireguard-tools (for wg-quick)
  pacman:
    name:
      - wireguard-tools
    state: present

- name: Install wireguard-dkms for kernel versions less than 5.6
  pacman:
    name:
      - linux-headers
      - wireguard-dkms
    state: present
  when: ansible_facts.kernel is version('5.6', '<')
